/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Catalogos;

import Datos.Conexion;
import Utilerias.ModeloTabla;
import eva.MDIApplication;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author Paul
 */
public class Conaic_Areas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Conaic_Areas
     */
    // Variables de la clase
    Conexion database;
    ResultSet registros;
    String idSeccion=""; 
    boolean filtrar=false;     //Jazz


    public Conaic_Areas() {
        initComponents();
        //bdMySQL = new Conexion();
        //bdMySQL.conectar();
        // Conectar a la BD
        database = MDIApplication.database;
        int sizeFont = tabla.getFont().getSize()+4;
        tabla.setRowHeight((tabla.getRowHeight() * 2)+sizeFont);      
        tabla.setDefaultRenderer(Object.class, new Utilerias.JerarquiaCellRenderer());
        cargarTabla();
    }    
    public static void main(String[] args){
        java.awt.EventQueue.invokeLater(new Runnable(){
            @Override
            public void run(){
                new Conaic_Areas().setVisible(true);
            }
                });       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barra = new javax.swing.JToolBar();
        nuevo = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        imprimir = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        CajaBusqueda = new javax.swing.JTextField();
        btn_Buscar = new javax.swing.JButton();
        campo = new javax.swing.JComboBox<>();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Areas de conocimiento de Conaic");
        setName("conaic_areas"); // NOI18N

        barra.setBackground(new java.awt.Color(102, 102, 102));
        barra.setFloatable(false);
        barra.setRollover(true);

        nuevo.setBackground(new java.awt.Color(102, 102, 102));
        nuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nuevo.png"))); // NOI18N
        nuevo.setText("Nuevo");
        nuevo.setFocusable(false);
        nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        barra.add(nuevo);

        editar.setBackground(new java.awt.Color(102, 102, 102));
        editar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Editar.png"))); // NOI18N
        editar.setText("Editar");
        editar.setFocusable(false);
        editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        barra.add(editar);

        borrar.setBackground(new java.awt.Color(102, 102, 102));
        borrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Baja.png"))); // NOI18N
        borrar.setText("Borrar");
        borrar.setFocusable(false);
        borrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        borrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        barra.add(borrar);

        imprimir.setBackground(new java.awt.Color(102, 102, 102));
        imprimir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Print.png"))); // NOI18N
        imprimir.setText("Imprimir");
        imprimir.setFocusable(false);
        imprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barra.add(imprimir);

        salir.setBackground(new java.awt.Color(102, 102, 102));
        salir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        salir.setText("Salir");
        salir.setFocusable(false);
        salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        barra.add(salir);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Area", "SubArea", "SubAreaArea", "Nombre", "Clave", "Title 7"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        CajaBusqueda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_Buscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Buscar.setText("Buscar");
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });

        campo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1264, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CajaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Buscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CajaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Buscar)))
                .addGap(27, 27, 27))
        );

        setSize(new java.awt.Dimension(1280, 736));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        // Busqueda por patron de caracteres. Jaz
        if (CajaBusqueda.getText().isEmpty())
          filtrar = false;
        else
          filtrar = true;
        cargarTabla();
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
        Catalogos.Conaic_Area dlgArea = new Catalogos.Conaic_Area();
        dlgArea.enlace=database;
        dlgArea.configurarPara("NUEVO");
        dlgArea.setTitle("Nuevo registro");
        dlgArea.padre = this;
        dlgArea.setLocationRelativeTo(this);
        dlgArea.setVisible(true); 
    }//GEN-LAST:event_nuevoActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:
         // Primeramente vemos si está seleccionado un registro
        int registroActivo = tabla.getSelectedRow();

        if (registroActivo == -1)
        {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún área de conocimiento",
                                          "Mensaje", JOptionPane.WARNING_MESSAGE);
            return;
        }        
         
        // Aquí vamos a editar el registro seleccionado
        Conaic_Area dlgArea = new Conaic_Area();
        dlgArea.enlace=database;
        int idx;        
        idx = tabla.convertRowIndexToModel(registroActivo);
        idx = (int)((ModeloTabla)tabla.getModel()).getValueAt(idx, 0);
        dlgArea.configurarPara("EDITAR");        
        dlgArea.setTitle("Editar");
        dlgArea.padre = this;
        dlgArea.cargarCampos(idx);
        dlgArea.setLocationRelativeTo(this);
        dlgArea.setVisible(true);        
        
    }//GEN-LAST:event_editarActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
         int registroActivo = tabla.getSelectedRow();

        if (registroActivo == -1)
        {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún área de conocimiento",
                                          "Mensaje", JOptionPane.WARNING_MESSAGE);
            return;
        }        
         
        // Aquí vamos a editar el registro seleccionado
        Conaic_Area dlgArea = new Conaic_Area();
        dlgArea.enlace=database;
        int idx;        
        idx = tabla.convertRowIndexToModel(registroActivo);
        idx = (int)((ModeloTabla)tabla.getModel()).getValueAt(idx, 0);
        dlgArea.validarnivel(idx);
        dlgArea.configurarPara("ELIMINAR");        
        dlgArea.setTitle("Eliminar área de conocimiento");
        dlgArea.padre = this;
        dlgArea.cargarCampos(idx);
        dlgArea.setLocationRelativeTo(this);
        dlgArea.setVisible(true);   
    }//GEN-LAST:event_borrarActionPerformed

    private void CajaBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaBusquedaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CajaBusqueda;
    private javax.swing.JToolBar barra;
    private javax.swing.JButton borrar;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JComboBox<String> campo;
    private javax.swing.JButton editar;
    private javax.swing.JButton imprimir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nuevo;
    private javax.swing.JButton salir;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

    public void cargarTabla()
    {         
      // Ejecutar metodo para recuperar los registros de la tabla de las Personas
      Datos.Conaic_Area oArea = new Datos.Conaic_Area(database);
      try{
          if(filtrar){
              if(campo.getSelectedIndex()==0){
                  try
                {
                   Integer.parseInt(CajaBusqueda.getText());
                }
                catch (NumberFormatException error)
                {
                   JOptionPane.showMessageDialog(this, "Patrón de búsqueda incorrecto, se esperaban números", "Error", JOptionPane.ERROR_MESSAGE);
                   filtrar=false;
                   return;     
                }
              }
              registros = oArea.DataSetConaic_Areas(CajaBusqueda.getText(), campo.getSelectedIndex()); 
          }
          else{
              registros = oArea.DataSetConaic_Areas();
          }
      }
      catch(SQLException ex){
           Logger.getLogger(Egel_Areas.class.getName()).log(Level.SEVERE, null, ex);
      }
      // Se crea una manejador para los datos que van a recuperarse
      ModeloTabla modelo = new ModeloTabla();   
      //tabla.getTableHeader().setReorderingAllowed(false);
      modelo.rs = registros;
 
      try 
        {
         modelo.rsmd=registros.getMetaData();
        } 
      catch (SQLException ex) 
        {
         Logger.getLogger(Conaic_Areas.class.getName()).log(Level.SEVERE, null, ex);
        }
      DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
      centerRenderer.setHorizontalAlignment( JLabel.CENTER );
      tabla.setModel(modelo);  
      tabla.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
      tabla.removeColumn(tabla.getColumnModel().getColumn(0));
      tabla.getColumnModel().getColumn(0).setPreferredWidth(75); 
      tabla.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
      tabla.getColumnModel().getColumn(1).setPreferredWidth(75);
      tabla.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
      tabla.getColumnModel().getColumn(2).setPreferredWidth(75);
      tabla.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
      tabla.getColumnModel().getColumn(3).setPreferredWidth(350);
      tabla.getColumnModel().getColumn(4).setPreferredWidth(100);
      tabla.getColumnModel().getColumn(5).setPreferredWidth(600);
      
    } 
   
}
